version: '3'

services:
  dsw:
    image: josefdolezal/dsw-local
    ports:
     - "8080:80"
     - "8081:8081"
    volumes: .:/src
    links:
     - rabbbit
     - mongo
  rabbit:
    image: "rabbitmq:3-management"
    ports:
     - "9090:15672"
    environment:
      RABBITMQ_DEFAULT_USER: usr
      RABBITMQ_DEFAULT_PASS: usr
    expose:
      - "5672"
  mongo:
    image: "mongo:latest"
    environment:
      MONGO_INITDB_ROOT_USERNAME: usr
      MONGO_INITDB_ROOT_PASSWORD: usr
    expose:
      - "27017"