version: '3'

services:
  rabbit:
    image: "rabbitmq:3-management"
    ports:
     - "15672:15672"
     - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: usr
      RABBITMQ_DEFAULT_PASS: usr
  mongo:
    image: "mongo:latest"
    environment:
      MONGO_INITDB_ROOT_USERNAME: usr
      MONGO_INITDB_ROOT_PASSWORD: usr
      MONGO_INITDB_DATABASE: dsw-server
    ports:
      - "27017:27017"